#!/bin/bash
NAME=mariadb10
IMAGE=mariadb
TAG=10.3.14
ARGS=
MOUNT_SOURCE=/mnt/disks/data/mariadb10
MOUNT_TARGET=/var/lib/mysql
PORT_SOURCE=3306
PORT_TARGET=3306

docker pull $IMAGE:$TAG
docker stop $NAME
docker rm $NAME
docker run -d --env MYSQL_ROOT_PASSWORD=root --restart=always --name=$NAME -p $PORT_SOURCE:$PORT_TARGET -v $MOUNT_SOURCE:$MOUNT_TARGET $IMAGE:$TAG $ARGS
