#!/bin/bash
NAME=postgres11
IMAGE=postgres
TAG=11.3
ARGS=
MOUNT_SOURCE=/mnt/disks/data/postgres11
MOUNT_TARGET=/var/lib/postgresql/data
PORT_SOURCE=5432
PORT_TARGET=5432

docker pull $IMAGE:$TAG
docker stop $NAME
docker rm $NAME
docker run -d --restart=always --name=$NAME -p $PORT_SOURCE:$PORT_TARGET -v $MOUNT_SOURCE:$MOUNT_TARGET $IMAGE:$TAG $ARGS
