#!/bin/bash
NAME=redis5
IMAGE=redis
TAG=5.0.5
ARGS="--databases 1 --maxmemory 500mb --maxmemory-policy allkeys-lru --appendonly yes"
MOUNT_SOURCE=/mnt/disks/data/redis5
MOUNT_TARGET=/data
PORT_SOURCE=6379
PORT_TARGET=6379

docker pull $IMAGE:$TAG
docker stop $NAME
docker rm $NAME
docker run -d --restart=always --name=$NAME -p $PORT_SOURCE:$PORT_TARGET -v $MOUNT_SOURCE:$MOUNT_TARGET $IMAGE:$TAG $ARGS
