#!/bin/bash
NAME=wordpress
IMAGE=wordpress
TAG=latest
ARGS=
MOUNT_SOURCE=/mnt/disks/data/wordpress
MOUNT_TARGET=/var/www/html
PORT_SOURCE=8080
PORT_TARGET=80

docker pull $IMAGE:$TAG
docker stop $NAME
docker rm $NAME
docker run -d --restart=always --name=$NAME -p $PORT_SOURCE:$PORT_TARGET -v $MOUNT_SOURCE:$MOUNT_TARGET $IMAGE:$TAG $ARGS
